install.packages(c("av","arules","biotools","car","caret","chemometrics","class","corrplot","corpus","data.table","devtools","descr","dplyr","emojifont","extrafont","factoextra","FactoMineR","flexdashboard","ggraph","ggthemes","ggTimeSeries","here","httr","igraph","jsonlite","KoNLP","lubridate","mice","mlbench","mosaic","mosaicData","multifluo","MVN","MVT","nparcomp","openxlsx","plotly","plyr","qqplotr","randomForest","raster","rayshader","RColorBrewer","RcppMeCab","readxl","reshape","reshape2","rgdal","rJava","RmecabKo","rpart","RSelenium","rtweet","rvest","shiny","shinydashboard","SnowballC","stringr","tidygraph","tidytext","tidyverse","tm","twitteR","waffle","wordcloud","wordcloud2","ztable"))

devtools::install_github("cardiomoon/ztable")

library(av)
library(arules)
library(biotools)
library(car)
library(caret)
library(chemometrics)
library(class)
library(corrplot)
library(corpus)
library(data.table)
library(devtools)
library(descr)
library(DMwR)
library(dplyr)
library(emojifont)
library(extrafont)
library(factoextra)
library(FactoMineR)
library(flexdashboard)
library(ggraph)
library(ggthemes)
library(ggTimeSeries)
library(here)
library(httr)
library(igraph)
library(jsonlite)
library(KoNLP)
library(lubridate)
library(mice)
library(mlbench)
library(mosaic)
library(mosaicData)
library(multifluo)
library(MVN)
library(MVT)
library(nparcomp)
library(openxlsx)
library(plotly)
library(plyr)
library(qqplotr)
library(randomForest)
library(raster)
library(rayshader)
library(RColorBrewer)
library(readxl)
library(reshape)
library(reshape2)
library(rgdal)
library(rJava)
library(RmecabKo)
library(rpart)
library(RSelenium)
library(rtweet)
library(rvest)
library(shiny)
library(shinydashboard)
library(SnowballC)
library(stringr)
library(tidygraph)
library(tidytext)
library(tidyverse)
library(tm)
library(twitteR)
library(waffle)
library(wordcloud)
library(wordcloud2)
library(xml2)
library(ztable)
library(magrittr)



#### KoNLP 사전작업



install_mecab("C:/Rlibs/mecab") 
devtools::install_github('haven-jeon/NIADic/NIADic', build_vignettes = TRUE)
Sys.setenv(JAVA_HOME='C:/Program Files/Java/jre1.8.0_241') 
buildDictionary(ext_dic = "woorimalsam") 
useNIADic()