install.packages(c("av","arules","biotools","base64enc","car","caret","chemometrics","class","corrplot","corpus","data.table","devtools","descr","dplyr","DMwR","emojifont","extrafont","factoextra","FactoMineR","flexdashboard","ggraph","ggthemes","ggTimeSeries","here","httr","htmlwidgets","htmltools","igraph","jsonlite","KoNLP","lubridate","mice","mlbench","mosaic","mosaicData","multifluo","MVN","MVT","nparcomp","openxlsx","plotly","plyr","profileR","qqplotr","randomForest","raster","rayshader","RColorBrewer","RcppMeCab","readxl","reshape","reshape2","rgdal","rJava","RmecabKo","rpart","RSelenium","rtweet","rvest","shiny","shinydashboard","SnowballC","stringr","tidygraph","tidytext","tidyverse","tm","twitteR","waffle","wordcloud","wordcloud2","yaml","ztable"))

install.packages("jsonlite")
install.packages("alr3")
install.packages("leaps")
install.packages("SnowballC")
install.packages("topicmodels")
install.packages("qdap")
install.packages("twitterR")

library(alr3)
library(av)
library(arules)
library(biotools)
library(car)
library(caret)
library(chemometrics)
library(class)
library(corrplot)
library(corpus)
library(data.table)
library(devtools)
library(descr)
library(DMwR)
library(dplyr)
library(emojifont)
library(extrafont)
library(factoextra)
library(FactoMineR)
library(flexdashboard)
library(ggraph)
library(ggthemes)
library(ggTimeSeries)
library(here)
library(httr)
library(igraph)
library(jsonlite)
library(lubridate)
library(leaps)
library(mice)
library(mlbench)
library(mosaic)
library(mosaicData)
library(multifluo)
library(MVN)
library(MVT)
library(nparcomp)
library(openxlsx)
library(plotly)
library(plyr)
library(profileR)
library(qqplotr)
library(randomForest)
library(raster)
library(rayshader)
library(RColorBrewer)
library(readxl)
library(reshape)
library(reshape2)
library(rgdal)
library(rJava)
library(RmecabKo)
library(RcppMeCab)
library(rpart)
library(RSelenium)
library(rtweet)
library(rvest)
library(shiny)
library(shinydashboard)
library(SnowballC)
library(stringr)
library(tidygraph)
library(tidytext)
library(tidyverse)
library(tm)
library(twitteR)
library(waffle)
library(wordcloud)
library(wordcloud2)
library(xml2)
library(ztable)
library(magrittr)
library(multilinguer)
library(KoNLP)
library(wordcloud2)
library(htmlwidgets)
library(jsonlite)
library(yaml)
library(base64enc)
library(qdap)
library(topicmodels)


Sys.setenv(JAVA_HOME='C:/Program Files/Java/jre1.8.0_251') 
buildDictionary(ext_dic = "woorimalsam") 
useNIADic()



#### KoNLP 사전작업
install.packages("multilinguer")
install_jdk()
install.packages(c('stringr', 'hash', 'tau', 'Sejong', 'RSQLite', 'devtools'), type = "binary")
install.packages("remotes")
remotes::install_github('haven-jeon/KoNLP', upgrade = "never", INSTALL_opts=c("--no-multiarch"))
library(KoNLP)

devtools::install_github('haven-jeon/NIADic/NIADic', build_vignettes = TRUE)
Sys.setenv(JAVA_HOME='C:/Program Files/Java/jre1.8.0_251') 
buildDictionary(ext_dic = "woorimalsam") 
useNIADic()


#### RBERT
devtools::install_github("jonathanbratt/RBERT", build_vignettes = TRUE)
tensorflow::install_tensorflow(version = "1.13.1")
devtools::install_github("rstudio/reticulate")

devtools::install_github("jonathanbratt/RBERTviz",build_vignettes = TRUE)


#### keras
install.packages('devtools')
install.packages("keras")
devtools::install_github("rstudio/keras")
library(keras)
library(zeallot)
library(tensorflow)

mnist <- dataset_mnist()

install.packages("purrr")
library(purrr)

install.packages("tokenizers")
library(tokenizers)
library(readr)


### tensorflow
install.packages("tensorflow")
library("tensorflow")
install_keras()
